package entity;
// Generated 2020-12-5 17:03:02 by Hibernate Tools 4.3.1

import java.util.List;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.RequestScoped;
import service.DataCRUDImp;




/**
 * Product generated by hbm2java
 */
@ManagedBean
@RequestScoped
public class Product  implements java.io.Serializable {


     private String PIdent;
     private String PName;
     private Double PPrice;
     private Integer PQuantity;
     private String PTime;
     private List<Product> list =null;
    public Product() {
    }
   public String displayAll() {
        DataCRUDImp s = new DataCRUDImp();
        this.list = s.selectAll();
        return "check";
    }
    
   public String modifyPro() {
        DataCRUDImp s = new DataCRUDImp();
        Product v = s.selectPro(this.PIdent);
        if(v==null)
            return "shibai";
        else if("".equals(this.PIdent))
            return "shibai";
        else
            s.modifyPro(this.PIdent,this.PName,this.PPrice,this.PQuantity,this.PTime);
            return "checkPu";
    }
   
    public String addCommit() {
        DataCRUDImp s = new DataCRUDImp();
        Product c = s.addProduct( this.getPName(), this.getPIdent(),this.getPPrice(), this.getPQuantity(),this.getPTime());
        return "check";
    }
    public String deletComit(){
        DataCRUDImp s = new DataCRUDImp();
        Product c = s.deletProduct( this.getPIdent());
        return "Success";
    }
    public Product(String PIdent) {
        this.PIdent = PIdent;
    }
    public Product(String PIdent, String PName, Double PPrice, Integer PQuantity, String PTime) {
       this.PIdent = PIdent;
       this.PName = PName;
       this.PPrice = PPrice;
       this.PQuantity = PQuantity;
       this.PTime = PTime;
    }

    public List<Product> getList() {
        return list;
    }

    public void setList(List<Product> list) {
        this.list = list;
    }
   
    public String getPIdent() {
        return this.PIdent;
    }
    
    public void setPIdent(String PIdent) {
        this.PIdent = PIdent;
    }
    public String getPName() {
        return this.PName;
    }
    
    public void setPName(String PName) {
        this.PName = PName;
    }
    public Double getPPrice() {
        return this.PPrice;
    }
    
    public void setPPrice(Double PPrice) {
        this.PPrice = PPrice;
    }
    public Integer getPQuantity() {
        return this.PQuantity;
    }
    
    public void setPQuantity(Integer PQuantity) {
        this.PQuantity = PQuantity;
    }
    public String getPTime() {
        return this.PTime;
    }
    
    public void setPTime(String PTime) {
        this.PTime = PTime;
    }

    @Override
    public String toString() {
        return "Product{" + "PIdent=" + PIdent + ", PName=" + PName + ", PPrice=" + PPrice + ", PQuantity=" + PQuantity + ", PTime=" + PTime + ", list=" + list + '}';
    }

}


