package entity;
// Generated 2020-12-5 17:03:02 by Hibernate Tools 4.3.1

import java.util.List;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.RequestScoped;
import service.DataCRUDImp;




/**
 * UserAdm generated by hbm2java
 */
@ManagedBean
@RequestScoped
public class UserAdm  implements java.io.Serializable {

     static UserAdm useradm;
     private String id;
     private String sign;
     private String password;
     private String address;
     private String telephone;
     private String name;
     private List<UserAdm> list =null;
    public UserAdm() {
    }
    
    public String loginUser() {
        DataCRUDImp s = new DataCRUDImp();
        useradm = s.login1(this.getId(), this.getPassword());
        if (useradm != null) {
            return "index";
        } else {
            return "denglushibai";
        }
    }
//    
//    public static void main(String[] args) {
//        DataCRUDImp s = new DataCRUDImp();
//         s.modifyUser("root","101");
//         System.out.println("chenggong");
//    }
   public String modifyUser() {
        DataCRUDImp s = new DataCRUDImp();
        UserAdm v = s.selectAdm(useradm.getId());
        if(v.getSign().equals("root")&&"root".equals(this.sign))
        { 
            s.modifyUser(this.sign, this.id);
            return "checkPu";
        }
       else
        return "shibai1";
    }
   
    public String userAll() {
        DataCRUDImp s = new DataCRUDImp();
        this.list = s.selectuser();
        return "check1";
    }
    
    public String addUser() {
        DataCRUDImp s = new DataCRUDImp();
        UserAdm c = s.adduser(this.getId(), this.getPassword(), this.getAddress(), this.getTelephone(), this.getName());
        return "yonghuzhuce";
    }
   public String root() {
        DataCRUDImp s = new DataCRUDImp();
        UserAdm c = s.selectId(useradm.getId());
        if(c.getSign().equals("root"))
        {
        return "add";
        }
        else{
           return "wuquanxian";
        }
    }
   public String root1() {
        DataCRUDImp s = new DataCRUDImp();
        UserAdm c = s.selectId(useradm.getId());
        if(c.getSign().equals("root"))
        {
        return "delete";
        }
        else{
           return "wuquanxian";
        }
    }
   public String root2() {
        DataCRUDImp s = new DataCRUDImp();
        UserAdm c = s.selectId(useradm.getId());
        if(c.getSign().equals("root"))
        {
        return "modify";
        }
        else{
           return "wuquanxian";
        }
    }
   public String root3() {
        DataCRUDImp s = new DataCRUDImp();
        UserAdm c = s.selectId(useradm.getId());
        if(c.getSign().equals("root"))
        {
        return "checkPu";
        }
        else{
           return "wuquanxian";
        }
    }
   
    public String deletuser(){
        DataCRUDImp s = new DataCRUDImp();
        UserAdm c = s.deletUser( this.getId());
        return "Success";
    }
    
    @Override
    public String toString() {
        return "UserAdm{" + "id=" + id + ", sign=" + sign + ", password=" + password + ", address=" + address + ", telephone=" + telephone + ", name=" + name + ", list=" + list + '}';
    }
    
    public List<UserAdm> getList() {
        return list;
    }

    public void setList(List<UserAdm> list) {
        this.list = list;
    }
    
    public UserAdm(String id, String password) {
        this.id = id;
        this.password = password;
    }
    
    public UserAdm(String id) {
        this.id = id;
    }
    public UserAdm(String id, String sign, String password, String address, String telephone, String name) {
       this.id = id;
       this.sign = sign;
       this.password = password;
       this.address = address;
       this.telephone = telephone;
       this.name = name;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getSign() {
        return this.sign;
    }
    
    public void setSign(String sign) {
        this.sign = sign;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getTelephone() {
        return this.telephone;
    }
    
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }




}


